* JBoss EAP 6
** Installation unter Windows
*** Installation des JBoss EAP 7
*** Einrichtung eines Windows-Dienst
* JBoss EAP 7
** Installation unter Windows

*** Installation des JBoss EAP 7
Es ist zu bestimmen, welche JBoss EAP-Version installiert werden soll, wo der JBoss EAP installiert werden soll und wo das Zip zu finden ist.
#+BEGIN_SRC powershell
$jboss_version = "7.1.0"
$jboss_install_dir = "D:\jboss"
$jboss_zip_dir = "D:\tmp"
#+END_SRC

Nun muss der JBoss EAP nur noch entpackt werde.
#+BEGIN_SRC powershell
...
#+END_SRC

*** Einrichtung eines Windows-Dienst
Zunächst sind die Systemvariablen ~JBOSS_HOME~ und ~NOPAUSE~ zu setzen.
#+BEGIN_SRC powershell
$env:JBOSS_HOME = "D:\jboss\jboss-eap-7.1"
[Environment]::SetEnvironmentVariable( "JBOSS_HOME", $env:JBOSS_HOME, [System.EnvironmentVariableTarget]::Machine) 

$env:NOPAUSE = 1
[Environment]::SetEnvironmentVariable( "NOPAUSE", $env:NOPAUSE, [System.EnvironmentVariableTarget]::Machine) 
#+END_SRC

Zum Erstellen des Windows-Dienst wird das /JBoss Core Services Jsvc Package/ verwendet, das von [[https://access.redhat.com/jbossnetwork/restricted/listSoftware.html][RedHat]] heruntergeladen werden kann. Es ist ebenfalls unter dem ~$jboss_install_dir~ zu entpacken, sodass sich z.B. die folgende Verzeichnisstuktur ergibt.
#+BEGIN_SRC
D:\jboss
├── jboss-eap-7.1
│   ├── bin
│   └── ...
└── jbcs-jsvc-1.0
#+END_SRC

Der folgende Befehl richtet den JBoss EAP als Windows-Dienst mit dem Namen ~jboss~ ein.
#+BEGIN_SRC powershell
D:\jboss\jboss-eap-7.1\bin\service.bat install /name jboss
#+END_SRC

Das erfolgreiche Einrichten des Windows-Diensts wird mit der Ausgabe der Parameter bestätigt, die an ~prunsrv.exe~ übergebenen wurden.
#+BEGIN_SRC powershell
prunsrv.exe install JBoss  
--DisplayName=JBoss 
--Description="JBoss Enterprise Application Platform 7" 
--LogLevel=INFO 
--LogPath="D:\jboss\jboss-eap-7.1\standalone\log" 
--LogPrefix=service 
--StdOutput=auto 
--StdError=auto 
--StartMode=exe 
--Startup=manual 
--StartImage=cmd.exe 
--StartPath="D:\jboss\jboss-eap-7.1\bin" ++StartParams="/c#set#NOPAUSE=Y#&&#standalone.bat#-Djboss.server.base.dir=D:\jboss\jboss-eap-7.1\standalone#
--server-config=standalone.xml" 
--StopMode=exe 
--StopImage=cmd.exe 
--StopPath="D:\jboss\jboss-eap-7.1\bin"  ++StopParams="/c jboss-cli.bat --controller=localhost:9990 --connect  --command=:shutdown"
Service JBoss installed
#+END_SRC
