#+TITLE: MySQL
* Benutzung
** Data Query Language (DQL)

*** SHOW DATABASES
#+BEGIN_SRC sql
SHOW DATABASES;
#+END_SRC

*** USE
#+BEGIN_SRC sql
USE employees;
#+END_SRC

*** SHOW TABLES
#+BEGIN_SRC sql
SHOW TABLES;
#+END_SRC

*** DESCRIBE
#+BEGIN_SRC sql
-- Beispiele für alle Tabellen
DESCRIBE departments;
DESCRIBE dept_emp;
DESCRIBE dept_manager;
DESCRIBE employees;
DESCRIBE salaries;
DESCRIBE titles;
-- Beispiele für alle Views
DESCRIBE current_dept_emp;
DESCRIBE departments dept_emp_latest_date;
#+END_SRC

*** SELECT
**** Implizite  SELECTs
#+BEGIN_SRC sql
-- Beispiele für alle Tabellen
SELECT * FROM	departments;
SELECT * FROM	dept_emp;
SELECT * FROM	dept_manager;
SELECT * FROM	employees;
SELECT * FROM	salaries;
SELECT * FROM	titles;
-- Beispiele für alle Views
SELECT * FROM	current_dept_emp;
SELECT * FROM	dept_emp_latest_date;
#+END_SRC

**** Explizite  SELECTs
#+BEGIN_SRC sql
-- Beispiel für die Tabelle 'employees'
SELECT	emp_no,
	birth_date,
	first_name,
	last_name,
	gender,
	hire_date *
FROM
	employees;
#+END_SRC
*** LIMIT
#+BEGIN_SRC sql
-- Beispiel für ein SELECT mit LIMIT auf die Tabelle 'employees'
SELECT * FROM employees LIMIT 1;
SELECT * FROM employees LIMIT 10;
SELECT * FROM employees LIMIT 100;
#+END_SRC


*** DISTINCT
#+BEGIN_SRC sql
-- Beispiel für select ohne DISTINCT
SELECT
	gender
FROM
	employees;
	
-- Beispiel für select mit DISTINCT
SELECT DISTINCT
	gender
FROM
	employees;
#+END_SRC

*** WHERE
#+BEGIN_SRC sql
SELECT
	*
FROM
	employees
WHERE
	gender = "F";
#+END_SRC

*** LIKE
#+BEGIN_SRC sql
SELECT
	*
FROM
	employees
WHERE
	first_name LIKE 'a%';
#+END_SRC

*** AND
#+BEGIN_SRC sql
SELECT
	*
FROM
	employees
WHERE
	gender = "F"
AND first_name LIKE 'a%';
#+END_SRC

*** OR
#+BEGIN_SRC sql
SELECT
	*
FROM
	employees
WHERE
	gender = "F"
OR first_name LIKE 'a%';
#+END_SRC

*** IN
#+BEGIN_SRC sql
SELECT
	*
FROM
	departments
WHERE
	dept_name IN ('Sales', 'Finance');
#+END_SRC

*** BETWEEN
#+BEGIN_SRC sql
SELECT
	*
FROM
	employees
WHERE
	hire_date BETWEEN '1994-01-01'
AND '1994-12-31';
#+END_SRC

*** ORDER BY
#+BEGIN_SRC sql
-- Eine aufsteigende Sortierung ist der Standard.
SELECT
	*
FROM
	employees
ORDER BY
	hire_date;
-- Eine aufsteigende Sortierung explizit angegeben.
SELECT
	*
FROM
	employees
ORDER BY
	hire_date ASC;
-- Eine absteigende Sortierung explizit angegeben.
SELECT
	*
FROM
	employees
ORDER BY
	hire_date DESC;
#+END_SRC
*** ALIAS
*** JOIN
**** INNER JOIN
**** LEFT JOIN
**** RIGHT JOIN
**** CROSS JOIN
**** SELF JOIN
*** GROUP BY
*** HAVING
*** Subqueries
*** UNION
*** MINUS
*** INTERSECT
** Data Manipulation Language (DML)
*** INSERT
*** LAST_INSERT_ID Function
*** UPDATE
*** UPDATE JOIN
*** DELETE
*** DELETE JOIN
*** ON DELETE CASCADE
*** REPLACE
** Data Control Language (DCL)
** DTL (Data Transaction Language)
* Installation

** Installation unter Debian
#+BEGIN_SRC sh
sudo apt install mysql-server
#+END_SRC

** Installation unter Windows
...

* Administration

** Benutzer und Rechte
*** Benutzer user@localhost mit dem Passwort password anlegen
#+BEGIN_SRC sql
CREATE USER 'user'@'localhost' IDENTIFIED BY 'password';
#+END_SRC

*** Aktuellen Benutzer anzeigen
#+BEGIN_SRC sql
SELECT USER();
#+END_SRC

*** Rechte eines Benutzers anzeigen
#+BEGIN_SRC sql
SHOW GRANTS;
#+END_SRC
#+BEGIN_SRC sql
SHOW GRANTS FOR 'root'@'localhost';
#+END_SRC

** Character Set und Collation

*** Konfigurierte Character Sets

Die konfigurierten Character Sets lassen sich mit dem folgendnen Befehl anzeigen.

#+BEGIN_SRC sql
SHOW GLOBAL VARIABLES LIKE 'character_set\_%';
#+END_SRC

Außer bei ~character_set_filesystem~ und ~character_set_system~ sollte hier alles auf ~utf8mb4~ stehen.

*** ~DEFAULT_CHARACTER_SET_NAME~ und ~DEFAULT_COLLATION_NAME~ für Datenbanken anzeigen

Der ~DEFAULT_CHARACTER_SET_NAME~ und der ~DEFAULT_COLLATION_NAME~ für Datenbanken lassen sich mit dem folgendnen Befehl anzeigen.

#+BEGIN_SRC sql
SELECT
	schema_name,
	default_character_set_name,
	DEFAULT_COLLATION_NAME
FROM
	information_schema.SCHEMATA
ORDER BY
	schema_name;
#+END_SRC

Hier sollte für eigene Datenbanken ~default_character_set_name~ auf ~utf8mb4~ und der ~default_collation_name~ auf ~utf8mb4_0900_ai_ci~ stehen.


*** ~character_set_name~ und ~collation_name~ für Tabellen anzeigen

Der ~character_set_name~ und der ~collation_name~ der Tabellen lassen sich mit dem folgendnen Befehl anzeigen.

#+BEGIN_SRC sql
SELECT
	T.table_schema,
	lower(t.TABLE_NAME),
	CCSA.character_set_name,
	CCSA.collation_name
FROM
	information_schema.`TABLES` T
INNER JOIN information_schema.`COLLATION_CHARACTER_SET_APPLICABILITY` CCSA ON CCSA.collation_name = T.table_collation
AND T.table_schema = 'db_name';
#+END_SRC

Hier sollte für die  ~character_set_name~ auf ~utf8mb4~ und der ~collation_name~ auf ~utf8mb4_0900_ai_ci~ stehen.

** Server SQL Modes
...
* Anwendung

* Monitoring

* Backups

** Logisches Backup mit /mysqldump/
Für das Erstellen eines Backups mit /mysqldump/ werden, je nach Anwendung verschiedene Rechte vorausgesetzt.
- SELECT zum Sichern von Tabellen
- SHOW VIEWS zum Sichern von Views
- TRIGGERS zum Sichern von Triggern
- LOCK TABLES zum Sperren von Tabellen
Für das Einspielen eines Backups mit /mysql/ ist das CREATE-Recht notwending.

*** Erstellen ein logischen Backups

**** Sichern einer Datenbank.
#+BEGIN_SRC sh
mysqldump db_name
#+END_SRC

**** Sichern mehrerer Tabellen einer Datenbank
#+BEGIN_SRC sh
mysqldump db_name tbl_name tb2_name...
#+END_SRC

**** Sichern aller Datenbanken
#+BEGIN_SRC sh
mysqldump --all-databases
#+END_SRC

*** Erstellen eines logischen Backups zur Datensicherung
#+BEGIN_SRC sh
mysqldump \
--user=root \
--all-databases \
--single-transaction \
--triggers \
--routines \
--events \
--hex-blob \
--no-data \
-r dump.sql
#+END_SRC

*** Erstellen eines logischen Backups ohne Daten
#+BEGIN_SRC sh
mysqldump \
--user=root \
--single-transaction \
--triggers \
--routines \
--events \
--hex-blob \
--no-data \
-r dump.sql \
db_name
#+END_SRC

*** Erstellen eines logischen Backups ohne CREATE-Statements
#+BEGIN_SRC sh
mysqldump \
--user=root \
--single-transaction \
--no-create-info=true \
-r dump.sql \
db_name
#+END_SRC

** Physikalisches Backup
...
