#+TITLE: PostgreSQL

* Installation
** Installation unter Windows

- [[https://www.openscg.com/bigsql/postgresql/installers/][PostgreSQL für Windows]]
- [[https://postgis.net/windows_downloads/][PostGIS für Windows]]
- [[https://stackoverflow.com/questions/42806784/how-to-alter-the-path-for-postgres-looking-for-extensions][Bug]]
- [[https://www.postgresql.org/ftp/pgadmin/pgadmin4/v3.0/windows/][pgadmin4]]

* Konfiguration

** Konfigurationsdateien
- postgresql.conf
- pg_hba.conf
- pg_ident.conf

** max_connections (postgresql.conf)
#+BEGIN_SRC sh
max_connections = 100			# (change requires restart)
superuser_reserved_connections = 3	# (change requires restart)
#+END_SRC

** shared_buffers (postgresql.conf)
Der Wert für /shared_buffers/ sollte ein Zehntel bis ein Viertel der RAM betragen.
#+BEGIN_SRC sh
shared_buffers = 128MB      # min 128kB
                            # (change requires restart)
#+END_SRC

** effective_cache_size (postgresql.conf)
Der Wert für /effective_cache_size/ sollte die Hälfte bis drei Viertel der RAM betragen.
#+BEGIN_SRC sh
effective_cache_size = 4GB
#+END_SRC

* Anwendung
* Monitoring
* Backups
** SQL Dump

*** Sichern und Zurückspielen einer Datenbank
Sichern der Datenbank /dbname/ in die Datei /dumpfile/.
#+BEGIN_SRC sh
pg_dump dbname > dumpfile
#+END_SRC
Zurückspielen der Datenbank /dbname/ aus der Datei /dumpfile/.
#+BEGIN_SRC sh
psql dbname < dumpfile
#+END_SRC
Zurückspielen der Datenbank /dbname/ aus der Datei /dumpfile/ mit Abbruch im Fehlerfall.
#+BEGIN_SRC sh
psql --set ON_ERROR_STOP=on dbname < dumpfile
#+END_SRC

*** Sichern und Zurückspielen aller Datenbanken
Sichern aller Datenbanken in die Datei /dumpfile/.
#+BEGIN_SRC sh
pg_dumpall > dumpfile
#+END_SRC
Zurückspielen aller Datenbanken aus der Datei /dumpfile/.
#+BEGIN_SRC sh
psql -f dumpfile postgres
#+END_SRC
Sichern aller Cluster-weiten Daten ohne die eigentlichen Datenbanken in die Datei /dumpfile/.
#+BEGIN_SRC sh
pg_dumpall --globals-only > dumpfile
#+END_SRC

*** Sichern und Zurückspielen mit Kompression
Sichern der Datenbank /dbname/ in die Datei /dumpfile/ im /custom/-Format, dass standardmäßig komprimiert ist.
#+BEGIN_SRC sh
pg_dump -Fc dbname > filename
#+END_SRC
Zurückspielen der Datenbank /dbname/ aus der im /custom/-Format gespeicherten Datei /dumpfile/.
#+BEGIN_SRC sh
pg_restore -d dbname filename
#+END_SRC

** Point-in-Time Recovery
